In [1]:
import torch

inputs = torch.tensor(
  [[0.43, 0.15, 0.89], # Your     (x^1)
   [0.55, 0.87, 0.66], # journey  (x^2)
   [0.57, 0.85, 0.64], # starts   (x^3)
   [0.22, 0.58, 0.33], # with     (x^4)
   [0.77, 0.25, 0.10], # one      (x^5) 
   [0.05, 0.80, 0.55]] # step     (x^6)
)

## Calculating Attention scores

In [2]:
query=inputs[1]

attn_scores2=torch.empty(inputs.shape[0])

for id,val in enumerate(inputs):
    attn_scores2[id]=torch.dot(query,val)

print(attn_scores2)


tensor([0.9544, 1.4950, 1.4754, 0.8434, 0.7070, 1.0865])


## Very basic normalization

In [3]:
attn_scores2_nor=attn_scores2/attn_scores2.sum()

In [4]:
attn_scores2_nor

tensor([0.1455, 0.2278, 0.2249, 0.1285, 0.1077, 0.1656])

In [5]:
attn_scores2_nor.sum()

tensor(1.0000)

## Naive Softmax

In [6]:
def softmax_naive(x):
    return torch.exp(x)/torch.exp(x).sum(dim=0)

attn_weights_2_naive = softmax_naive(attn_scores2)

print("Attention weights:", attn_weights_2_naive)
print("Sum:", attn_weights_2_naive.sum())

Attention weights: tensor([0.1385, 0.2379, 0.2333, 0.1240, 0.1082, 0.1581])
Sum: tensor(1.)


## PyTorch Softmax

In [7]:
attn_weights_2_pt=torch.softmax(attn_scores2,dim=0)

In [8]:
attn_weights_2_pt

tensor([0.1385, 0.2379, 0.2333, 0.1240, 0.1082, 0.1581])

In [9]:
attn_weights_2_pt.sum()

tensor(1.)

## Calculating Context Vector 

In [ ]:
query=inputs[1]

context_vector2=torch.empty(inputs.shape)

for id,val in enumerate(inputs):
    context_vector2[id]+=