In [1]:
vocab_size=50257
vec_dim=768

In [2]:
import torch

torch.manual_seed(123)

embedding_layer=torch.nn.Embedding(vocab_size,vec_dim)

In [3]:
embedding_layer.weight

Parameter containing:
tensor([[ 3.3737e-01, -1.7778e-01, -3.0353e-01,  ..., -3.1812e-01,
         -1.3936e+00,  5.2262e-01],
        [ 2.5787e-01,  3.4197e-01, -8.1678e-01,  ..., -4.0981e-01,
          4.9785e-01, -3.7207e-01],
        [ 7.9574e-01,  5.3501e-01,  9.4275e-01,  ..., -1.0749e+00,
          9.5492e-02, -1.4138e+00],
        ...,
        [-7.1278e-01, -5.0190e-01,  1.4119e+00,  ..., -1.4979e-01,
         -4.8977e-01, -1.0620e+00],
        [ 2.0646e+00,  1.1190e+00,  3.8486e-01,  ..., -7.2015e-01,
         -5.5703e-01,  9.8639e-01],
        [ 1.1364e-03, -7.5320e-01, -1.7924e-01,  ..., -3.2443e-01,
          2.6055e-01,  5.8885e-01]], requires_grad=True)

In [4]:
len(embedding_layer.weight[0])

768

In [5]:
len(embedding_layer.weight)

50257

In [8]:
embedding_layer(torch.tensor([3]))

tensor([[-3.1186e-02,  1.6913e+00, -2.2380e+00,  1.5100e+00, -1.3988e+00,
         -8.6170e-02, -1.0665e+00,  3.9668e-01,  4.3065e-01, -4.1438e-01,
         -3.1839e-01,  2.0454e+00,  7.2016e-01, -8.5287e-01,  5.8417e-01,
         -7.2265e-01, -1.4753e+00,  6.8972e-02,  8.0555e-01,  1.3240e+00,
         -9.8045e-01, -1.2199e+00, -9.3244e-01, -5.0473e-01, -7.9787e-01,
          2.2975e-01,  4.1912e-01,  2.7533e-01,  3.4339e-02, -1.4618e+00,
          1.3078e+00,  3.2857e-01, -2.2494e-01, -2.8510e+00, -2.4963e-01,
         -9.1632e-01,  2.1671e+00, -9.3249e-01,  1.9403e+00,  1.1822e+00,
         -2.3286e+00,  4.1231e-02, -1.0138e+00,  8.3503e-02, -1.4837e+00,
         -5.5533e-01, -1.9864e+00,  1.4011e+00, -1.8653e+00,  4.0254e-03,
          4.1516e-01, -6.6000e-01, -1.0517e+00,  5.8994e-01,  2.8082e-01,
         -2.2997e-01, -5.4657e-01,  1.6418e+00,  4.0352e-01,  1.4848e+00,
         -9.1545e-01, -5.3633e-01, -3.1294e-01,  1.2653e+00, -2.5450e+00,
          6.8583e-01, -2.1797e-02, -3.

In [9]:
embedding_layer(torch.tensor([3])).shape

torch.Size([1, 768])

## Here we are taking input IDs 1,2,3,4 just for example 

In [12]:
embedding_layer(torch.tensor([1,2,3,4]))

tensor([[ 0.2579,  0.3420, -0.8168,  ..., -0.4098,  0.4978, -0.3721],
        [ 0.7957,  0.5350,  0.9427,  ..., -1.0749,  0.0955, -1.4138],
        [-0.0312,  1.6913, -2.2380,  ...,  0.2379, -1.1839, -0.3179],
        [ 0.4279,  1.1632, -0.8327,  ...,  0.1802,  0.1917,  0.8713]],
       grad_fn=<EmbeddingBackward0>)

In [13]:
embedding_layer(torch.tensor([1,2,3,4])).shape

torch.Size([4, 768])

### We will fetch Input token Id matrix from dataloader, like the one we created in the Input_Output_Pair.ipynb . Here I am taking a example matrix just to avoid making dataloader class again.

In [16]:
input=torch.tensor([[   40,   367,  2885,  1464],
            [ 1807,  3619,   402,   271],
            [10899,  2138,   257,  7026],
            [15632,   438,  2016,   257],
            [  922,  5891,  1576,   438],
            [  568,   340,   373,   645],
            [ 1049,  5975,   284,   502],
            [  284,  3285,   326,    11]])

In [17]:
target=torch.tensor([[  367,  2885,  1464,  1807],
            [ 3619,   402,   271, 10899],
            [ 2138,   257,  7026, 15632],
            [  438,  2016,   257,   922],
            [ 5891,  1576,   438,   568],
            [  340,   373,   645,  1049],
            [ 5975,   284,   502,   284],
            [ 3285,   326,    11,   287]])

### Making token embedding matrix of the input tensor

In [18]:
token_embedding=embedding_layer(input)

In [20]:
token_embedding.shape

torch.Size([8, 4, 768])

### Making positional embedding matrix

In [21]:
context_length=4

positional_embedding_layer=torch.nn.Embedding(context_length,vec_dim)

In [22]:
positional_embedding=positional_embedding_layer(torch.arange(context_length))

In [23]:
positional_embedding

tensor([[ 0.8769,  0.2550,  0.8441,  ..., -1.0354,  1.3085,  1.7957],
        [-1.0029,  0.0995,  1.2459,  ...,  1.5453, -0.1126, -1.5197],
        [ 1.3317,  0.7561,  0.9077,  ...,  0.0830,  1.8336, -2.2225],
        [-1.2565, -2.0294, -1.3685,  ...,  1.8521,  0.5519,  0.8279]],
       grad_fn=<EmbeddingBackward0>)

In [24]:
positional_embedding.shape

torch.Size([4, 768])

### Adding token and positional embeddidng to get final input embedding

In [25]:
final_input_embedding=token_embedding+positional_embedding

In [27]:
final_input_embedding

tensor([[[-0.1799,  0.2253,  1.3451,  ..., -3.3624,  1.5512,  0.7479],
         [-0.4485, -1.0974,  0.3022,  ...,  0.8535, -0.9061, -2.4201],
         [ 0.4971,  1.2479, -0.1325,  ..., -0.7782,  1.7408, -3.7610],
         [-1.3202, -2.9181, -1.9827,  ...,  2.1475,  0.7441, -0.5098]],

        [[ 0.0637,  0.4153,  1.4359,  ..., -2.3947,  0.8759,  2.3597],
         [-0.7564, -1.7561,  0.9509,  ...,  1.0355,  1.8724,  0.3053],
         [ 0.7134,  0.0838,  2.0500,  ..., -0.8435,  2.3037, -4.2871],
         [ 0.3270, -1.1483, -0.0661,  ...,  2.2471,  3.3361, -0.7091]],

        [[ 0.1530,  0.9897,  1.3508,  ...,  0.3902,  2.3604,  2.5972],
         [-1.0236, -0.4338,  0.4297,  ...,  1.4121, -1.0205, -0.5917],
         [ 2.6075,  0.4664,  1.8617,  ...,  0.4235,  0.7700, -2.2899],
         [-1.5242, -1.6866, -1.4792,  ...,  2.3230, -0.2393,  0.9393]],

        ...,

        [[ 0.8192, -1.4678,  0.6342,  ..., -0.2623,  0.3787,  1.5812],
         [-0.8294,  1.0581,  2.4514,  ...,  2.9168,  0.01

In [28]:
final_input_embedding.shape

torch.Size([8, 4, 768])